/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Pages.customer;
import Models.Muncipality.CitizenInfo;
import Models.Muncipality.CitizenInfoDirectory;
import Models.User.RoleType;
import Models.User.StaffUser;
import Models.User.User;
import Models.Utility.MaintenanceRequest;
import Pages.Login;
import java.text.MessageFormat;
import java.time.LocalDate;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author vatsalkapadia
 */
public class customerJFrame extends javax.swing.JFrame {
    ArrayList<User> mockCitizenUserList = new ArrayList();
    public static User currentUser;
    

    /**
     * Creates new form customerJFrame
     */
    public customerJFrame() {
        initComponents();
         // Initialize ui
        nameLabel.setText(currentUser.getCitizenInfo().getName());
        nameLabel1.setText(currentUser.getCitizenInfo().getName());
        usernameMProfile.setText(currentUser.getUsername());
        nameMProfile.setText(currentUser.getCitizenInfo().getName());
        ssnMProfile.setText(currentUser.getCitizenInfo().getSsn());
//        dobMProfile.setText(currentUser.getCitizenInfo().getBirthDate().toString());
//        houseIDMProfile.setText(currentUser.getCitizenInfo().getHouse().houseId);
//        houseAreaMProfile.setText(currentUser.getCitizenInfo().getHouse().cityArea);
//        houseAddL1MProfile.setText(currentUser.getCitizenInfo().getHouse().addressOne);
//        houseAddL2MProfile.setText(currentUser.getCitizenInfo().getHouse().addressTwo);
    }
    
    
    public static void setCurrentUser(User user) {
        currentUser = user;
        System.out.println("Current User:");
        System.out.println(currentUser.getUsername());
        if (currentUser.getRole().equals(RoleType.Customer)) {
            System.out.println(currentUser.getUsername());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        utilityTabButton = new javax.swing.JPanel();
        utilityTabLabel = new javax.swing.JLabel();
        billingTabButton = new javax.swing.JPanel();
        billingTabLabel = new javax.swing.JLabel();
        profileTabButton = new javax.swing.JPanel();
        profileTabLabel = new javax.swing.JLabel();
        logoutjButton2 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        bankingServicejPanel4 = new javax.swing.JPanel();
        newSupportRequestButton = new javax.swing.JButton();
        jComboBox2 = new javax.swing.JComboBox<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        utilityServicejPanel5 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        requestField = new javax.swing.JTextArea();
        submitMaintenanceRequest = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        requestDropdown = new javax.swing.JComboBox<>();
        myProfileRedirectionjPanel6 = new javax.swing.JPanel();
        nameLabel = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        myProfilejPanel4 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        nameLabel1 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        usernameMProfile = new javax.swing.JTextField();
        nameMProfile = new javax.swing.JTextField();
        ssnMProfile = new javax.swing.JTextField();
        dobMProfile = new javax.swing.JTextField();
        houseIDMProfile = new javax.swing.JTextField();
        houseAreaMProfile = new javax.swing.JTextField();
        houseAddL1MProfile = new javax.swing.JTextField();
        houseAddL2MProfile = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(0, 0, 0));

        utilityTabButton.setBackground(new java.awt.Color(102, 102, 102));
        utilityTabButton.setForeground(new java.awt.Color(255, 255, 255));
        utilityTabButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                utilityTabButtonMousePressed(evt);
            }
        });

        utilityTabLabel.setForeground(new java.awt.Color(255, 255, 255));
        utilityTabLabel.setText("Utility Services");
        utilityTabLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                utilityTabLabelMousePressed(evt);
            }
        });

        javax.swing.GroupLayout utilityTabButtonLayout = new javax.swing.GroupLayout(utilityTabButton);
        utilityTabButton.setLayout(utilityTabButtonLayout);
        utilityTabButtonLayout.setHorizontalGroup(
            utilityTabButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(utilityTabButtonLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(utilityTabLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        utilityTabButtonLayout.setVerticalGroup(
            utilityTabButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, utilityTabButtonLayout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addComponent(utilityTabLabel)
                .addContainerGap())
        );

        billingTabButton.setBackground(new java.awt.Color(102, 102, 102));
        billingTabButton.setForeground(new java.awt.Color(255, 255, 255));
        billingTabButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                billingTabButtonMousePressed(evt);
            }
        });

        billingTabLabel.setForeground(new java.awt.Color(255, 255, 255));
        billingTabLabel.setText("Billing Services");
        billingTabLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                billingTabLabelMousePressed(evt);
            }
        });

        javax.swing.GroupLayout billingTabButtonLayout = new javax.swing.GroupLayout(billingTabButton);
        billingTabButton.setLayout(billingTabButtonLayout);
        billingTabButtonLayout.setHorizontalGroup(
            billingTabButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(billingTabButtonLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(billingTabLabel)
                .addContainerGap(50, Short.MAX_VALUE))
        );
        billingTabButtonLayout.setVerticalGroup(
            billingTabButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, billingTabButtonLayout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addComponent(billingTabLabel)
                .addContainerGap())
        );

        profileTabButton.setBackground(new java.awt.Color(102, 102, 102));
        profileTabButton.setForeground(new java.awt.Color(255, 255, 255));
        profileTabButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                profileTabButtonMousePressed(evt);
            }
        });

        profileTabLabel.setForeground(new java.awt.Color(255, 255, 255));
        profileTabLabel.setText("My Profile");
        profileTabLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                profileTabLabelMousePressed(evt);
            }
        });

        javax.swing.GroupLayout profileTabButtonLayout = new javax.swing.GroupLayout(profileTabButton);
        profileTabButton.setLayout(profileTabButtonLayout);
        profileTabButtonLayout.setHorizontalGroup(
            profileTabButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(profileTabButtonLayout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(profileTabLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        profileTabButtonLayout.setVerticalGroup(
            profileTabButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, profileTabButtonLayout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addComponent(profileTabLabel)
                .addContainerGap())
        );

        logoutjButton2.setBackground(new java.awt.Color(0, 51, 51));
        logoutjButton2.setForeground(new java.awt.Color(255, 255, 255));
        logoutjButton2.setText("LOGOUT");
        logoutjButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutjButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(utilityTabButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(billingTabButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(profileTabButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(logoutjButton2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(231, 231, 231)
                .addComponent(utilityTabButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(billingTabButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(profileTabButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 115, Short.MAX_VALUE)
                .addComponent(logoutjButton2)
                .addGap(52, 52, 52))
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 170, -1));

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 70));

        bankingServicejPanel4.setBackground(new java.awt.Color(51, 51, 51));

        newSupportRequestButton.setText("+ Submit Feedback");
        newSupportRequestButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                newSupportRequestButtonMousePressed(evt);
            }
        });
        newSupportRequestButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newSupportRequestButtonActionPerformed(evt);
            }
        });

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5" }));

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane3.setViewportView(jTextArea2);

        jLabel5.setText("Rating");

        jLabel6.setText("How would you rate your experience today?");

        javax.swing.GroupLayout bankingServicejPanel4Layout = new javax.swing.GroupLayout(bankingServicejPanel4);
        bankingServicejPanel4.setLayout(bankingServicejPanel4Layout);
        bankingServicejPanel4Layout.setHorizontalGroup(
            bankingServicejPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bankingServicejPanel4Layout.createSequentialGroup()
                .addGroup(bankingServicejPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bankingServicejPanel4Layout.createSequentialGroup()
                        .addGap(238, 238, 238)
                        .addGroup(bankingServicejPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(newSupportRequestButton)
                            .addGroup(bankingServicejPanel4Layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(bankingServicejPanel4Layout.createSequentialGroup()
                        .addGap(175, 175, 175)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(bankingServicejPanel4Layout.createSequentialGroup()
                        .addGap(266, 266, 266)
                        .addComponent(jLabel5))
                    .addGroup(bankingServicejPanel4Layout.createSequentialGroup()
                        .addGap(160, 160, 160)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(191, Short.MAX_VALUE))
        );
        bankingServicejPanel4Layout.setVerticalGroup(
            bankingServicejPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bankingServicejPanel4Layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(jLabel5)
                .addGap(28, 28, 28)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(70, 70, 70)
                .addComponent(newSupportRequestButton)
                .addGap(86, 86, 86))
        );

        jTabbedPane1.addTab("tab1", bankingServicejPanel4);

        utilityServicejPanel5.setBackground(new java.awt.Color(51, 51, 51));

        requestField.setColumns(20);
        requestField.setRows(5);
        jScrollPane1.setViewportView(requestField);

        submitMaintenanceRequest.setText("Submit");
        submitMaintenanceRequest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitMaintenanceRequestActionPerformed(evt);
            }
        });

        jLabel1.setText("New Request");

        requestDropdown.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Electrical", "Heating", "Plumbing" }));

        javax.swing.GroupLayout utilityServicejPanel5Layout = new javax.swing.GroupLayout(utilityServicejPanel5);
        utilityServicejPanel5.setLayout(utilityServicejPanel5Layout);
        utilityServicejPanel5Layout.setHorizontalGroup(
            utilityServicejPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(utilityServicejPanel5Layout.createSequentialGroup()
                .addGroup(utilityServicejPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(utilityServicejPanel5Layout.createSequentialGroup()
                        .addGap(167, 167, 167)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(utilityServicejPanel5Layout.createSequentialGroup()
                        .addGap(252, 252, 252)
                        .addComponent(submitMaintenanceRequest))
                    .addGroup(utilityServicejPanel5Layout.createSequentialGroup()
                        .addGap(219, 219, 219)
                        .addComponent(requestDropdown, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(utilityServicejPanel5Layout.createSequentialGroup()
                        .addGap(242, 242, 242)
                        .addComponent(jLabel1)))
                .addContainerGap(215, Short.MAX_VALUE))
        );
        utilityServicejPanel5Layout.setVerticalGroup(
            utilityServicejPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(utilityServicejPanel5Layout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addComponent(jLabel1)
                .addGap(45, 45, 45)
                .addComponent(requestDropdown, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(65, 65, 65)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(67, 67, 67)
                .addComponent(submitMaintenanceRequest)
                .addContainerGap(77, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("tab2", utilityServicejPanel5);

        myProfileRedirectionjPanel6.setBackground(new java.awt.Color(51, 51, 51));

        nameLabel.setBackground(new java.awt.Color(51, 51, 51));
        nameLabel.setForeground(new java.awt.Color(255, 255, 255));
        nameLabel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameLabelActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Date", "Type", "Description", "Amount", "Status"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        jLabel4.setText("Bills");

        jLabel18.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jLabel18.setText("Bank Account #");

        jLabel17.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jLabel17.setText("Balance");

        jButton1.setText("Pay Bill");

        javax.swing.GroupLayout myProfileRedirectionjPanel6Layout = new javax.swing.GroupLayout(myProfileRedirectionjPanel6);
        myProfileRedirectionjPanel6.setLayout(myProfileRedirectionjPanel6Layout);
        myProfileRedirectionjPanel6Layout.setHorizontalGroup(
            myProfileRedirectionjPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(myProfileRedirectionjPanel6Layout.createSequentialGroup()
                .addGroup(myProfileRedirectionjPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(myProfileRedirectionjPanel6Layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(nameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(myProfileRedirectionjPanel6Layout.createSequentialGroup()
                        .addGap(259, 259, 259)
                        .addComponent(jLabel4)))
                .addContainerGap(67, Short.MAX_VALUE))
            .addGroup(myProfileRedirectionjPanel6Layout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addGroup(myProfileRedirectionjPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(myProfileRedirectionjPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(myProfileRedirectionjPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1)
                        .addGap(106, 106, 106))))
        );
        myProfileRedirectionjPanel6Layout.setVerticalGroup(
            myProfileRedirectionjPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(myProfileRedirectionjPanel6Layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(jLabel4)
                .addGroup(myProfileRedirectionjPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(myProfileRedirectionjPanel6Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(nameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(myProfileRedirectionjPanel6Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(31, 31, 31)
                .addGroup(myProfileRedirectionjPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addGap(18, 18, 18)
                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(94, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("tab3", myProfileRedirectionjPanel6);

        myProfilejPanel4.setBackground(new java.awt.Color(51, 51, 51));

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("HELLO");

        nameLabel1.setBackground(new java.awt.Color(51, 51, 51));
        nameLabel1.setForeground(new java.awt.Color(255, 255, 255));
        nameLabel1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameLabel1ActionPerformed(evt);
            }
        });

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setFont(new java.awt.Font("Helvetica Neue", 0, 15)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Username");

        jLabel9.setBackground(new java.awt.Color(255, 255, 255));
        jLabel9.setFont(new java.awt.Font("Helvetica Neue", 0, 15)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Name");

        jLabel10.setBackground(new java.awt.Color(255, 255, 255));
        jLabel10.setFont(new java.awt.Font("Helvetica Neue", 0, 15)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("SSN");

        jLabel11.setBackground(new java.awt.Color(255, 255, 255));
        jLabel11.setFont(new java.awt.Font("Helvetica Neue", 0, 15)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("DOB");

        jLabel12.setBackground(new java.awt.Color(255, 255, 255));
        jLabel12.setFont(new java.awt.Font("Helvetica Neue", 0, 15)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("House ID");

        jLabel13.setBackground(new java.awt.Color(255, 255, 255));
        jLabel13.setFont(new java.awt.Font("Helvetica Neue", 0, 15)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Housing Area");

        jLabel14.setBackground(new java.awt.Color(255, 255, 255));
        jLabel14.setFont(new java.awt.Font("Helvetica Neue", 0, 15)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("House Address ");

        jLabel15.setBackground(new java.awt.Color(255, 255, 255));
        jLabel15.setFont(new java.awt.Font("Helvetica Neue", 0, 15)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("House Address");

        jLabel16.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("MY PROFILE");

        javax.swing.GroupLayout myProfilejPanel4Layout = new javax.swing.GroupLayout(myProfilejPanel4);
        myProfilejPanel4.setLayout(myProfilejPanel4Layout);
        myProfilejPanel4Layout.setHorizontalGroup(
            myProfilejPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(myProfilejPanel4Layout.createSequentialGroup()
                .addGroup(myProfilejPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(myProfilejPanel4Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(myProfilejPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(myProfilejPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(nameLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(myProfilejPanel4Layout.createSequentialGroup()
                                .addGroup(myProfilejPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(myProfilejPanel4Layout.createSequentialGroup()
                                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(dobMProfile, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(myProfilejPanel4Layout.createSequentialGroup()
                                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(ssnMProfile, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(myProfilejPanel4Layout.createSequentialGroup()
                                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(nameMProfile, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(myProfilejPanel4Layout.createSequentialGroup()
                                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(usernameMProfile, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(42, 42, 42)
                                .addGroup(myProfilejPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(28, 28, 28)
                                .addGroup(myProfilejPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(houseAddL2MProfile, javax.swing.GroupLayout.DEFAULT_SIZE, 164, Short.MAX_VALUE)
                                    .addComponent(houseAddL1MProfile)
                                    .addComponent(houseAreaMProfile)
                                    .addComponent(houseIDMProfile)))))
                    .addGroup(myProfilejPanel4Layout.createSequentialGroup()
                        .addGap(245, 245, 245)
                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(64, Short.MAX_VALUE))
        );
        myProfilejPanel4Layout.setVerticalGroup(
            myProfilejPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(myProfilejPanel4Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel16)
                .addGap(60, 60, 60)
                .addGroup(myProfilejPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(nameLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(myProfilejPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel12)
                    .addComponent(usernameMProfile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(houseIDMProfile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(myProfilejPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel13)
                    .addComponent(nameMProfile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(houseAreaMProfile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(myProfilejPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel14)
                    .addComponent(ssnMProfile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(houseAddL1MProfile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(myProfilejPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jLabel15)
                    .addComponent(dobMProfile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(houseAddL2MProfile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(165, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("tab4", myProfilejPanel4);

        jPanel1.add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 70, 630, 530));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void utilityTabLabelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_utilityTabLabelMousePressed
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(1);
    }//GEN-LAST:event_utilityTabLabelMousePressed

    private void utilityTabButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_utilityTabButtonMousePressed
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(1);
    }//GEN-LAST:event_utilityTabButtonMousePressed

    private void billingTabButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_billingTabButtonMousePressed
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(2);
    }//GEN-LAST:event_billingTabButtonMousePressed

    private void billingTabLabelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_billingTabLabelMousePressed
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(2);
    }//GEN-LAST:event_billingTabLabelMousePressed

    private void profileTabButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_profileTabButtonMousePressed
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(2);
    }//GEN-LAST:event_profileTabButtonMousePressed

    private void profileTabLabelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_profileTabLabelMousePressed
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(2);
    }//GEN-LAST:event_profileTabLabelMousePressed

    private void logoutjButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutjButton2ActionPerformed
        // TODO add your handling code here:
        Login loginpg = new Login();
        loginpg.show();
        dispose();
    }//GEN-LAST:event_logoutjButton2ActionPerformed

    private void nameLabel1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameLabel1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameLabel1ActionPerformed

    private void nameLabelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameLabelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameLabelActionPerformed

    private void newSupportRequestButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_newSupportRequestButtonMousePressed
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_newSupportRequestButtonMousePressed

    private void newSupportRequestButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newSupportRequestButtonActionPerformed
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(1);
    }//GEN-LAST:event_newSupportRequestButtonActionPerformed

    private void submitMaintenanceRequestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitMaintenanceRequestActionPerformed
        // TODO add your handling code here:
        String requestType = requestDropdown.getSelectedItem().toString();
        String requestDetail = requestField.getSelectedText();
        CitizenInfo currentUserInfo = currentUser.getCitizenInfo();
        StaffUser defaultStaff = new StaffUser("Brian Lee", "Engineer", "339-415-5458", "blee", "blee", RoleType.UtilityManager);
        MaintenanceRequest request = new MaintenanceRequest("0000", LocalDate.now().toString(), requestType, requestDetail, defaultStaff, "Unpaid");
        request.setCustomerInfo(currentUserInfo);
        CitizenInfoDirectory.citizenRequests.add(request);
          JOptionPane.showMessageDialog(this, MessageFormat.format("{0} Request Successfully Created!", requestType));
          requestField.setText("");
        
        
    }//GEN-LAST:event_submitMaintenanceRequestActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(customerJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(customerJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(customerJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(customerJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new customerJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bankingServicejPanel4;
    private javax.swing.JPanel billingTabButton;
    private javax.swing.JLabel billingTabLabel;
    private javax.swing.JTextField dobMProfile;
    private javax.swing.JTextField houseAddL1MProfile;
    private javax.swing.JTextField houseAddL2MProfile;
    private javax.swing.JTextField houseAreaMProfile;
    private javax.swing.JTextField houseIDMProfile;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JButton logoutjButton2;
    private javax.swing.JPanel myProfileRedirectionjPanel6;
    private javax.swing.JPanel myProfilejPanel4;
    private javax.swing.JTextField nameLabel;
    private javax.swing.JTextField nameLabel1;
    private javax.swing.JTextField nameMProfile;
    private javax.swing.JButton newSupportRequestButton;
    private javax.swing.JPanel profileTabButton;
    private javax.swing.JLabel profileTabLabel;
    private javax.swing.JComboBox<String> requestDropdown;
    private javax.swing.JTextArea requestField;
    private javax.swing.JTextField ssnMProfile;
    private javax.swing.JButton submitMaintenanceRequest;
    private javax.swing.JTextField usernameMProfile;
    private javax.swing.JPanel utilityServicejPanel5;
    private javax.swing.JPanel utilityTabButton;
    private javax.swing.JLabel utilityTabLabel;
    // End of variables declaration//GEN-END:variables
}
