/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Pages.Utility;

import Models.User.StaffUser;
import Models.Utility.MaintenanceRequest;
import Models.Utility.MaintenanceRequestDirectory;
import Models.Utility.UtilityStaffDirectory;
import java.text.MessageFormat;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author thomaskojoaddaquay
 */
public class UtilityManager extends javax.swing.JFrame {
 ArrayList<MaintenanceRequest> allRequests= new MaintenanceRequestDirectory().getRequests();
 ArrayList<StaffUser> allStaff = new UtilityStaffDirectory().getAllStaff();
 MaintenanceRequest activeRequest;
 StaffUser activeStaff;
    /**
     * Creates new form UtilityManager
     */
    public UtilityManager() {
        initComponents();
        populateRequestsTable();
        populateStaffTable();
        setStaffDropDownOptions();
        hideRequestUpdatePanel();
    }
       public void populateRequestsTable() {
        DefaultTableModel model = (DefaultTableModel) requestsTable.getModel();
        model.setRowCount(0);
         System.out.println("Active request:");
                for (MaintenanceRequest request : allRequests)  {
                    Object[] row = new Object[6];
                        row[0] = request;
                        row[1] = request.date;
                        row[2] = request.type;
                        row[3] = request.description;
                        row[4] = request.assignedTo;
                        row[5] = request.status;
                        
                        model.addRow(row);
                }
    }
    
    public void populateStaffTable() {
        DefaultTableModel model = (DefaultTableModel) staffTable.getModel();
        model.setRowCount(0);
         System.out.println("Active staff:");
                for (StaffUser staff : allStaff)  {
                    Object[] row = new Object[4];
                        row[0] = staff;
                        row[1] = staff.getName();
                        row[2] = staff.getTitle();
                        row[3] = staff.getPhone();
                        model.addRow(row);
                }
    }
         public void setStaffDropDownOptions(){
         dropDownStaff.setModel(new DefaultComboBoxModel(_getStaffNames()));
         }
         
         public String[] _getStaffNames() {
            ArrayList<String> names = new ArrayList<String>();
         for (StaffUser staff: allStaff) {
              names.add("Unassigned");
             names.add(staff.getName());
         }
         String[] dropdownNames = names.toArray(new String[names.size()]);
         return dropdownNames;
         }
         
         public void hideRequestUpdatePanel() {
                requestDetailsPanel.setVisible(false);
                createBillButton.setVisible(false);
    }
         public void showRequestUpdatePanel() {
                requestDetailsPanel.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pagePanel = new javax.swing.JPanel();
        sideBarPanel = new javax.swing.JPanel();
        requestsTab = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        staffTab = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        logoutButton = new javax.swing.JButton();
        menuBarPanel = new javax.swing.JPanel();
        tabbedPane = new javax.swing.JTabbedPane();
        requestsPanel = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        requestsTable = new javax.swing.JTable();
        requestDetailsPanel = new javax.swing.JPanel();
        saveRequestButton = new javax.swing.JButton();
        dropDownStaff = new javax.swing.JComboBox<>();
        dropDownStatus = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        createBillButton = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        staffPanel = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        staffTable = new javax.swing.JTable();
        manageStaffPanel = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        updateStaffButton = new javax.swing.JButton();
        editStaffName = new javax.swing.JTextField();
        editStaffUsername = new javax.swing.JTextField();
        editStaffTitle = new javax.swing.JTextField();
        editStaffPhone = new javax.swing.JTextField();
        editStaffPassword = new javax.swing.JPasswordField();
        deleteStaffButton = new javax.swing.JButton();
        billingPanel = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        requestsTable1 = new javax.swing.JTable();
        newBillPanel = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        hoursField = new javax.swing.JTextField();
        rateField = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        billingRequestPanel = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        billingMeterNumberLabel = new javax.swing.JLabel();
        billingRequestTypeLabel = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        billingStaffLabel = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        billingStaffRoleLabel = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        billingDescriptionLabel = new javax.swing.JLabel();
        newBillBackButton = new javax.swing.JButton();
        calculateTotalButton = new javax.swing.JButton();
        totalPanel = new javax.swing.JPanel();
        totalBillLabel = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pagePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        sideBarPanel.setBackground(new java.awt.Color(0, 0, 0));
        sideBarPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        requestsTab.setBackground(new java.awt.Color(102, 102, 102));
        requestsTab.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                requestsTabMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                requestsTabMousePressed(evt);
            }
        });

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Requests");

        javax.swing.GroupLayout requestsTabLayout = new javax.swing.GroupLayout(requestsTab);
        requestsTab.setLayout(requestsTabLayout);
        requestsTabLayout.setHorizontalGroup(
            requestsTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(requestsTabLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel2)
                .addContainerGap(49, Short.MAX_VALUE))
        );
        requestsTabLayout.setVerticalGroup(
            requestsTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, requestsTabLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 18, Short.MAX_VALUE)
                .addContainerGap())
        );

        sideBarPanel.add(requestsTab, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 140, 30));

        jLabel4.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jLabel4.setText("Welcome!");
        sideBarPanel.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, -1, -1));

        staffTab.setBackground(new java.awt.Color(102, 102, 102));
        staffTab.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                staffTabMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                staffTabMousePressed(evt);
            }
        });

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Staff");

        javax.swing.GroupLayout staffTabLayout = new javax.swing.GroupLayout(staffTab);
        staffTab.setLayout(staffTabLayout);
        staffTabLayout.setHorizontalGroup(
            staffTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(staffTabLayout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(jLabel3)
                .addContainerGap(67, Short.MAX_VALUE))
        );
        staffTabLayout.setVerticalGroup(
            staffTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(staffTabLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addContainerGap(9, Short.MAX_VALUE))
        );

        sideBarPanel.add(staffTab, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 140, 30));

        logoutButton.setText("Logout");
        sideBarPanel.add(logoutButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 630, -1, -1));

        pagePanel.add(sideBarPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 140, 700));

        menuBarPanel.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout menuBarPanelLayout = new javax.swing.GroupLayout(menuBarPanel);
        menuBarPanel.setLayout(menuBarPanelLayout);
        menuBarPanelLayout.setHorizontalGroup(
            menuBarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 760, Short.MAX_VALUE)
        );
        menuBarPanelLayout.setVerticalGroup(
            menuBarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );

        pagePanel.add(menuBarPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 0, 760, 60));

        requestsPanel.setBackground(new java.awt.Color(51, 51, 51));

        jLabel5.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Maintenance Requests");

        requestsTable.setBackground(new java.awt.Color(51, 51, 51));
        requestsTable.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        requestsTable.setForeground(new java.awt.Color(255, 255, 255));
        requestsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Meter #", "Date", "Type", "Description", "Assigned To", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        requestsTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                requestsTableMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                requestsTableMousePressed(evt);
            }
        });
        jScrollPane2.setViewportView(requestsTable);
        if (requestsTable.getColumnModel().getColumnCount() > 0) {
            requestsTable.getColumnModel().getColumn(0).setResizable(false);
            requestsTable.getColumnModel().getColumn(1).setResizable(false);
            requestsTable.getColumnModel().getColumn(2).setResizable(false);
            requestsTable.getColumnModel().getColumn(3).setResizable(false);
            requestsTable.getColumnModel().getColumn(4).setResizable(false);
            requestsTable.getColumnModel().getColumn(5).setResizable(false);
        }

        requestDetailsPanel.setBackground(new java.awt.Color(51, 51, 51));

        saveRequestButton.setText("Save");
        saveRequestButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveRequestButtonActionPerformed(evt);
            }
        });

        dropDownStaff.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        dropDownStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Unassigned", "In Progress", "Complete" }));

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Assigned To");

        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Status");

        javax.swing.GroupLayout requestDetailsPanelLayout = new javax.swing.GroupLayout(requestDetailsPanel);
        requestDetailsPanel.setLayout(requestDetailsPanelLayout);
        requestDetailsPanelLayout.setHorizontalGroup(
            requestDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, requestDetailsPanelLayout.createSequentialGroup()
                .addGap(0, 158, Short.MAX_VALUE)
                .addGroup(requestDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dropDownStaff, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addGroup(requestDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dropDownStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(177, 177, 177))
            .addGroup(requestDetailsPanelLayout.createSequentialGroup()
                .addGap(245, 245, 245)
                .addComponent(saveRequestButton, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        requestDetailsPanelLayout.setVerticalGroup(
            requestDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(requestDetailsPanelLayout.createSequentialGroup()
                .addContainerGap(33, Short.MAX_VALUE)
                .addGroup(requestDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(requestDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dropDownStaff, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dropDownStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addComponent(saveRequestButton)
                .addGap(27, 27, 27))
        );

        createBillButton.setText("+ Estimate Bill");
        createBillButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                createBillButtonMousePressed(evt);
            }
        });
        createBillButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createBillButtonActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Update Request");

        javax.swing.GroupLayout requestsPanelLayout = new javax.swing.GroupLayout(requestsPanel);
        requestsPanel.setLayout(requestsPanelLayout);
        requestsPanelLayout.setHorizontalGroup(
            requestsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, requestsPanelLayout.createSequentialGroup()
                .addContainerGap(55, Short.MAX_VALUE)
                .addGroup(requestsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addGroup(requestsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(requestDetailsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 666, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(createBillButton, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(39, 39, 39))
            .addGroup(requestsPanelLayout.createSequentialGroup()
                .addGap(310, 310, 310)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        requestsPanelLayout.setVerticalGroup(
            requestsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(requestsPanelLayout.createSequentialGroup()
                .addGap(95, 95, 95)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(createBillButton)
                .addGap(13, 13, 13)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(requestDetailsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(59, Short.MAX_VALUE))
        );

        tabbedPane.addTab("tab1", requestsPanel);

        staffPanel.setBackground(new java.awt.Color(51, 51, 51));

        jLabel6.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Staff");

        staffTable.setBackground(new java.awt.Color(51, 51, 51));
        staffTable.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        staffTable.setForeground(new java.awt.Color(255, 255, 255));
        staffTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Username", "Name", "Title", "Phone"
            }
        ));
        staffTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                staffTableMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(staffTable);

        manageStaffPanel.setBackground(new java.awt.Color(51, 51, 51));

        jLabel20.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("Username");

        jLabel22.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("Password");

        jLabel25.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setText("Title");

        jLabel26.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setText("Phone");

        jLabel27.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(255, 255, 255));
        jLabel27.setText("Name");

        updateStaffButton.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        updateStaffButton.setText("Update");
        updateStaffButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                updateStaffButtonMousePressed(evt);
            }
        });
        updateStaffButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateStaffButtonActionPerformed(evt);
            }
        });

        deleteStaffButton.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        deleteStaffButton.setText("Delete");
        deleteStaffButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                deleteStaffButtonMousePressed(evt);
            }
        });

        javax.swing.GroupLayout manageStaffPanelLayout = new javax.swing.GroupLayout(manageStaffPanel);
        manageStaffPanel.setLayout(manageStaffPanelLayout);
        manageStaffPanelLayout.setHorizontalGroup(
            manageStaffPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(manageStaffPanelLayout.createSequentialGroup()
                .addGroup(manageStaffPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(manageStaffPanelLayout.createSequentialGroup()
                        .addGap(95, 95, 95)
                        .addGroup(manageStaffPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(manageStaffPanelLayout.createSequentialGroup()
                                .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(61, 61, 61)
                                .addComponent(jLabel25)
                                .addGap(106, 106, 106)
                                .addGroup(manageStaffPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(editStaffPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(manageStaffPanelLayout.createSequentialGroup()
                                .addComponent(jLabel20)
                                .addGap(57, 57, 57)
                                .addGroup(manageStaffPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(editStaffTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(manageStaffPanelLayout.createSequentialGroup()
                                        .addGap(43, 43, 43)
                                        .addGroup(manageStaffPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel22)
                                            .addComponent(editStaffPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addComponent(editStaffUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(editStaffName, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(manageStaffPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(deleteStaffButton))
                    .addGroup(manageStaffPanelLayout.createSequentialGroup()
                        .addGap(240, 240, 240)
                        .addComponent(updateStaffButton)))
                .addContainerGap(102, Short.MAX_VALUE))
        );
        manageStaffPanelLayout.setVerticalGroup(
            manageStaffPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(manageStaffPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(deleteStaffButton)
                .addGap(3, 3, 3)
                .addGroup(manageStaffPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26)
                    .addComponent(jLabel27)
                    .addComponent(jLabel25))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(manageStaffPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(editStaffName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(editStaffTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(editStaffPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(manageStaffPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(jLabel22))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(manageStaffPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(editStaffUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(editStaffPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addComponent(updateStaffButton)
                .addGap(16, 16, 16))
        );

        javax.swing.GroupLayout staffPanelLayout = new javax.swing.GroupLayout(staffPanel);
        staffPanel.setLayout(staffPanelLayout);
        staffPanelLayout.setHorizontalGroup(
            staffPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(staffPanelLayout.createSequentialGroup()
                .addGroup(staffPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(staffPanelLayout.createSequentialGroup()
                        .addGap(94, 94, 94)
                        .addGroup(staffPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(manageStaffPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 560, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(staffPanelLayout.createSequentialGroup()
                        .addGap(335, 335, 335)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(96, Short.MAX_VALUE))
        );
        staffPanelLayout.setVerticalGroup(
            staffPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(staffPanelLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(manageStaffPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(126, Short.MAX_VALUE))
        );

        tabbedPane.addTab("tab2", staffPanel);

        billingPanel.setBackground(new java.awt.Color(51, 51, 51));

        jLabel11.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel11.setText("Billing");

        requestsTable1.setBackground(new java.awt.Color(51, 51, 51));
        requestsTable1.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        requestsTable1.setForeground(new java.awt.Color(255, 255, 255));
        requestsTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Meter #", "Date", "Type", "Description", "Amount Due", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        requestsTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                requestsTable1MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                requestsTable1MousePressed(evt);
            }
        });
        jScrollPane3.setViewportView(requestsTable1);
        if (requestsTable1.getColumnModel().getColumnCount() > 0) {
            requestsTable1.getColumnModel().getColumn(0).setResizable(false);
            requestsTable1.getColumnModel().getColumn(1).setResizable(false);
            requestsTable1.getColumnModel().getColumn(2).setResizable(false);
            requestsTable1.getColumnModel().getColumn(3).setResizable(false);
            requestsTable1.getColumnModel().getColumn(4).setResizable(false);
            requestsTable1.getColumnModel().getColumn(5).setResizable(false);
        }

        javax.swing.GroupLayout billingPanelLayout = new javax.swing.GroupLayout(billingPanel);
        billingPanel.setLayout(billingPanelLayout);
        billingPanelLayout.setHorizontalGroup(
            billingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(billingPanelLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(billingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(billingPanelLayout.createSequentialGroup()
                        .addGap(278, 278, 278)
                        .addComponent(jLabel11))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 626, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(99, Short.MAX_VALUE))
        );
        billingPanelLayout.setVerticalGroup(
            billingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(billingPanelLayout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addComponent(jLabel11)
                .addGap(29, 29, 29)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(391, Short.MAX_VALUE))
        );

        tabbedPane.addTab("tab3", billingPanel);

        newBillPanel.setBackground(new java.awt.Color(51, 51, 51));

        jLabel12.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Hours ");

        jLabel13.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Rate");

        jLabel14.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Billing Estimator");

        billingRequestPanel.setBackground(new java.awt.Color(51, 51, 51));

        jLabel15.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Meter #");

        jLabel17.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Type");

        billingMeterNumberLabel.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        billingMeterNumberLabel.setForeground(new java.awt.Color(255, 255, 255));
        billingMeterNumberLabel.setText("0000000");

        billingRequestTypeLabel.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        billingRequestTypeLabel.setForeground(new java.awt.Color(255, 255, 255));
        billingRequestTypeLabel.setText("None");

        jLabel18.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Name");

        billingStaffLabel.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        billingStaffLabel.setForeground(new java.awt.Color(255, 255, 255));
        billingStaffLabel.setText("None");

        jLabel19.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Role");

        billingStaffRoleLabel.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        billingStaffRoleLabel.setForeground(new java.awt.Color(255, 255, 255));
        billingStaffRoleLabel.setText("None");

        jLabel16.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Description");

        billingDescriptionLabel.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        billingDescriptionLabel.setForeground(new java.awt.Color(255, 255, 255));
        billingDescriptionLabel.setText("None");

        javax.swing.GroupLayout billingRequestPanelLayout = new javax.swing.GroupLayout(billingRequestPanel);
        billingRequestPanel.setLayout(billingRequestPanelLayout);
        billingRequestPanelLayout.setHorizontalGroup(
            billingRequestPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(billingRequestPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(billingRequestPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15)
                    .addComponent(billingMeterNumberLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(billingStaffLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(billingRequestPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel17)
                    .addComponent(billingRequestTypeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(billingStaffRoleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(billingRequestPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel16)
                    .addComponent(billingDescriptionLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        billingRequestPanelLayout.setVerticalGroup(
            billingRequestPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(billingRequestPanelLayout.createSequentialGroup()
                .addGroup(billingRequestPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(billingRequestPanelLayout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(billingMeterNumberLabel)
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, billingRequestPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(billingRequestPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(billingRequestPanelLayout.createSequentialGroup()
                                .addComponent(jLabel16)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(billingDescriptionLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(billingRequestPanelLayout.createSequentialGroup()
                                .addComponent(jLabel17)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(billingRequestTypeLabel)))
                        .addGap(23, 23, 23)))
                .addGroup(billingRequestPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(billingRequestPanelLayout.createSequentialGroup()
                        .addComponent(jLabel18)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(billingStaffLabel))
                    .addGroup(billingRequestPanelLayout.createSequentialGroup()
                        .addComponent(jLabel19)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(billingStaffRoleLabel)))
                .addContainerGap(50, Short.MAX_VALUE))
        );

        newBillBackButton.setText("Back");
        newBillBackButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                newBillBackButtonMousePressed(evt);
            }
        });

        calculateTotalButton.setText("Calculate Total");
        calculateTotalButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                calculateTotalButtonMousePressed(evt);
            }
        });

        totalPanel.setBackground(new java.awt.Color(51, 51, 51));

        totalBillLabel.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        totalBillLabel.setForeground(new java.awt.Color(255, 255, 255));
        totalBillLabel.setText("0");

        jLabel23.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("$");

        jLabel21.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("Total");

        javax.swing.GroupLayout totalPanelLayout = new javax.swing.GroupLayout(totalPanel);
        totalPanel.setLayout(totalPanelLayout);
        totalPanelLayout.setHorizontalGroup(
            totalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, totalPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel21, javax.swing.GroupLayout.DEFAULT_SIZE, 76, Short.MAX_VALUE)
                .addGap(12, 12, 12)
                .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(totalBillLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36))
        );
        totalPanelLayout.setVerticalGroup(
            totalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(totalPanelLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(totalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(totalBillLabel)
                    .addComponent(jLabel23)
                    .addComponent(jLabel21))
                .addContainerGap(62, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout newBillPanelLayout = new javax.swing.GroupLayout(newBillPanel);
        newBillPanel.setLayout(newBillPanelLayout);
        newBillPanelLayout.setHorizontalGroup(
            newBillPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, newBillPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(newBillPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, newBillPanelLayout.createSequentialGroup()
                        .addGroup(newBillPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13)
                            .addComponent(rateField, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(newBillPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(newBillPanelLayout.createSequentialGroup()
                                .addComponent(hoursField, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(calculateTotalButton))
                            .addComponent(jLabel12))
                        .addGap(301, 301, 301))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, newBillPanelLayout.createSequentialGroup()
                        .addComponent(totalPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(278, 278, 278))))
            .addGroup(newBillPanelLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(newBillBackButton)
                .addGap(58, 58, 58)
                .addGroup(newBillPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(billingRequestPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(189, Short.MAX_VALUE))
        );
        newBillPanelLayout.setVerticalGroup(
            newBillPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(newBillPanelLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(newBillPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(newBillBackButton))
                .addGap(33, 33, 33)
                .addComponent(billingRequestPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(newBillPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(newBillPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rateField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hoursField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(calculateTotalButton))
                .addGap(34, 34, 34)
                .addComponent(totalPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(199, Short.MAX_VALUE))
        );

        tabbedPane.addTab("tab4", newBillPanel);

        pagePanel.add(tabbedPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 30, 760, 670));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pagePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pagePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void requestsTabMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_requestsTabMouseClicked
        // TODO add your handling code here:
      
    }//GEN-LAST:event_requestsTabMouseClicked

    private void staffTabMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_staffTabMouseClicked
        // TODO add your handling code here:
       
    }//GEN-LAST:event_staffTabMouseClicked

    private void requestsTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_requestsTableMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_requestsTableMouseClicked

    private void saveRequestButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveRequestButtonActionPerformed
        // TODO add your handling code here:
         int tableSize = requestsTable.getRowCount();
         int selectedRow = requestsTable.getSelectedRow();
         if (selectedRow >= 0 || selectedRow < tableSize) {
            MaintenanceRequest selectedRequest = (MaintenanceRequest) requestsTable.getValueAt(selectedRow, 0);
            String status = dropDownStatus.getSelectedItem().toString();
            String staffName = dropDownStaff.getSelectedItem().toString();
            StaffUser selectedStaff = null;
            for (StaffUser staff : allStaff) {
               if (staffName.equals(staff.getName())) {
                   selectedStaff = staff;
               }
           }
            selectedRequest.setAssignedTo(selectedStaff);
            selectedRequest.setStatus(status);
            populateRequestsTable();
         }
    }//GEN-LAST:event_saveRequestButtonActionPerformed

    private void requestsTableMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_requestsTableMousePressed
        // TODO add your handling code here:
         int tableSize = requestsTable.getRowCount();
         int selectedRow = requestsTable.getSelectedRow();
         System.out.println("Row");
         System.out.println(selectedRow);
         if (selectedRow >= 0 || selectedRow < tableSize) {
            MaintenanceRequest selectedRequest = (MaintenanceRequest) requestsTable.getValueAt(selectedRow, 0);
            dropDownStaff.setSelectedItem(selectedRequest.assignedTo.getName());
            dropDownStatus.setSelectedItem(selectedRequest.status);
            showRequestUpdatePanel();
            if ("Complete".equals(dropDownStatus.getSelectedItem().toString())) {
                createBillButton.setVisible(true);
            } else {
                createBillButton.setVisible(false);
            }
         }
    }//GEN-LAST:event_requestsTableMousePressed

    private void requestsTabMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_requestsTabMousePressed
        // TODO add your handling code here:
          tabbedPane.setSelectedIndex(0);
    }//GEN-LAST:event_requestsTabMousePressed

    private void staffTabMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_staffTabMousePressed
        // TODO add your handling code here:
         tabbedPane.setSelectedIndex(1);
    }//GEN-LAST:event_staffTabMousePressed

    private void createBillButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createBillButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_createBillButtonActionPerformed

    private void createBillButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_createBillButtonMousePressed
        // TODO add your handling code here:
        int selectedRow = requestsTable.getSelectedRow();
        MaintenanceRequest selectedRequest = (MaintenanceRequest) requestsTable.getValueAt(selectedRow, 0);
        activeRequest = selectedRequest;
        billingMeterNumberLabel.setText(selectedRequest.meterNumber);
        billingDescriptionLabel.setText(selectedRequest.description);
        billingRequestTypeLabel.setText(selectedRequest.type);
        billingStaffLabel.setText(selectedRequest.assignedTo.getName());
        billingStaffRoleLabel.setText(selectedRequest.assignedTo.getTitle());
        totalPanel.setVisible(false);
        tabbedPane.setSelectedIndex(3);
    }//GEN-LAST:event_createBillButtonMousePressed

    private void newBillBackButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_newBillBackButtonMousePressed
        // TODO add your handling code here:
        tabbedPane.setSelectedIndex(0);
    }//GEN-LAST:event_newBillBackButtonMousePressed

    private void calculateTotalButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_calculateTotalButtonMousePressed
        // TODO add your handling code here:
         String rate = rateField.getText();
         String hours = hoursField.getText();
          double hoursNum;
          double rateNum;
         // Validate rate & hours
        if ("".equals(rate) || rate == null) {
            JOptionPane.showMessageDialog(this, "Please enter rate", "Error", 0);
            return;
        }
        if ("".equals(hours) || hours == null) {
            JOptionPane.showMessageDialog(this, "Please enter hours", "Error", 0);
            return;
        }
        try {
            hoursNum = Double.parseDouble(hours);
        } 
        catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Invalid hours", "Error", 0);
             return;
        }
        try {
            rateNum = Double.parseDouble(rate);
        } 
        catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Invalid rate", "Error", 0);
             return;
        }
        // Calculate total
        double total = (hoursNum * rateNum);
        totalBillLabel.setText(Double.toString(total));
        totalPanel.setVisible(true);
    }//GEN-LAST:event_calculateTotalButtonMousePressed

    private void requestsTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_requestsTable1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_requestsTable1MouseClicked

    private void requestsTable1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_requestsTable1MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_requestsTable1MousePressed

    private void staffTableMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_staffTableMousePressed
        // TODO add your handling code here:
        int tableSize = staffTable.getRowCount();
        int selectedRow = staffTable.getSelectedRow();
            if (selectedRow >= 0 || selectedRow < tableSize) {
                StaffUser selectedStaff = (StaffUser) staffTable.getValueAt(selectedRow, 0);
                activeStaff = selectedStaff;
                editStaffUsername.setText(selectedStaff.getUsername());
                editStaffName.setText(selectedStaff.getName());
                editStaffPhone.setText(selectedStaff.getPhone());
                editStaffTitle.setText(selectedStaff.getTitle());
                editStaffPassword.setText(selectedStaff.getPassword());
         }       
    }//GEN-LAST:event_staffTableMousePressed

    private void updateStaffButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateStaffButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_updateStaffButtonActionPerformed

    private void updateStaffButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updateStaffButtonMousePressed
        // TODO add your handling code here:
        String _username = editStaffUsername.getText();
        String _name = editStaffName.getText();
        String _phone = editStaffPhone.getText();
        String _title = editStaffTitle.getText();
        String _password = editStaffPassword.getText();
        
        boolean isValidUpdate = validateUserEdit() ;
        if (isValidUpdate) {
            activeStaff.setUsername(_username);
            activeStaff.setName(_name);
            activeStaff.setPhone(_phone);
            activeStaff.setTitle(_title);
            activeStaff.setPassword(_password);
            populateStaffTable();
            JOptionPane.showMessageDialog(this, MessageFormat.format("{0} Successfully Updated!", _name));
        }
    }//GEN-LAST:event_updateStaffButtonMousePressed

    private void deleteStaffButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteStaffButtonMousePressed
        // TODO add your handling code here:
         JOptionPane.showMessageDialog(this, MessageFormat.format("{0} Successfully Updated!", activeStaff.getName()));
        allStaff.remove(activeStaff);
        populateStaffTable();
    }//GEN-LAST:event_deleteStaffButtonMousePressed
    
    public boolean validateUserEdit() {
        UtilityStaffDirectory userList = new UtilityStaffDirectory();
        String _username = editStaffUsername.getText();
        String _name = editStaffName.getText();
        String _phone = editStaffPhone.getText();
        String _title = editStaffTitle.getText();
        String _password = editStaffPassword.getText();
        
                // Validate username
        if ("".equals(_username) || _username == null) {
            // JOptionPane.showMessageDialog(this, "Error: Name is required");
            JOptionPane.showMessageDialog(this, "Username is required", "Error", 0);
            return false;
        }
         if (!userList.isUsernameUpdateValid(activeStaff, _username)) {
              JOptionPane.showMessageDialog(this, "Username already taken", "Error", 0);
             return false;
        } 
         // Validate name
        if ("".equals(_name) || _name == null) {
            JOptionPane.showMessageDialog(this, "Name is required", "Error", 0);
            return false;
        } 
           // Validate Phone
        if ("".equals(_phone) || _phone == null) {
            JOptionPane.showMessageDialog(this, "Phone is required", "Error", 0);
            return false;
        }
           // Validate Title
        if ("".equals(_title) || _title == null) {
            JOptionPane.showMessageDialog(this, "Title is required", "Error", 0);
            return false;
        }
             // Validate Password
        if ("".equals(_password) || _password == null) {
            JOptionPane.showMessageDialog(this, "Password is required", "Error", 0);
            return false;
        }
        return true;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UtilityManager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UtilityManager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UtilityManager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UtilityManager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UtilityManager().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel billingDescriptionLabel;
    private javax.swing.JLabel billingMeterNumberLabel;
    private javax.swing.JPanel billingPanel;
    private javax.swing.JPanel billingRequestPanel;
    private javax.swing.JLabel billingRequestTypeLabel;
    private javax.swing.JLabel billingStaffLabel;
    private javax.swing.JLabel billingStaffRoleLabel;
    private javax.swing.JButton calculateTotalButton;
    private javax.swing.JButton createBillButton;
    private javax.swing.JButton deleteStaffButton;
    private javax.swing.JComboBox<String> dropDownStaff;
    private javax.swing.JComboBox<String> dropDownStatus;
    private javax.swing.JTextField editStaffName;
    private javax.swing.JPasswordField editStaffPassword;
    private javax.swing.JTextField editStaffPhone;
    private javax.swing.JTextField editStaffTitle;
    private javax.swing.JTextField editStaffUsername;
    private javax.swing.JTextField hoursField;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JButton logoutButton;
    private javax.swing.JPanel manageStaffPanel;
    private javax.swing.JPanel menuBarPanel;
    private javax.swing.JButton newBillBackButton;
    private javax.swing.JPanel newBillPanel;
    private javax.swing.JPanel pagePanel;
    private javax.swing.JTextField rateField;
    private javax.swing.JPanel requestDetailsPanel;
    private javax.swing.JPanel requestsPanel;
    private javax.swing.JPanel requestsTab;
    private javax.swing.JTable requestsTable;
    private javax.swing.JTable requestsTable1;
    private javax.swing.JButton saveRequestButton;
    private javax.swing.JPanel sideBarPanel;
    private javax.swing.JPanel staffPanel;
    private javax.swing.JPanel staffTab;
    private javax.swing.JTable staffTable;
    private javax.swing.JTabbedPane tabbedPane;
    private javax.swing.JLabel totalBillLabel;
    private javax.swing.JPanel totalPanel;
    private javax.swing.JButton updateStaffButton;
    // End of variables declaration//GEN-END:variables
}
